sudo: true
dist: xenial
language: ruby
services:
- redis-server
- xvfb
jdk:
- openjdk11
rvm:
- 2.5.3
addons:
  chrome: stable
cache:
  bundler: true
  directories:
  - dep_cache
before_install:
- google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222
  http://localhost &
- mkdir -p dep_cache
- ls -l dep_cache
- cp config/travis/solr_wrapper_test.yml config/solr_wrapper_test.yml
- cp config/travis/fcrepo_wrapper_test.yml config/fcrepo_wrapper_test.yml
- gem update bundler
- gem update --system 3.0.6
- nvm install 12.9.0
before_script:
- export DISPLAY=:99.0
- RAILS_ENV=test bundle exec rake db:environment:set db:create db:migrate --trace
- RAILS_ENV=test npm install yarn
- RAILS_ENV=test yarn --ignore-engines install
- RAILS_ENV=test bundle exec rake webpacker:compile
script:
- bundle exec rake ci
deploy:
- provider: codedeploy
  access_key_id: AKIAJODP6VPR5EKCIJCQ
  secret_access_key:
    secure: secure: "JxYaqSvi2BVWdqlKPKFjtjb7QU8oVzzt9EDn9IczD/mXameOpdHqUr41R/02wPTBcizAYd+ya6bAtKQlarZJK87Vrz96sYk2gBRNbEEtXkxla+g6/VN3mk3sXmc5DUwwIAwyRS1hp7EAp8arjMP2eMe48LZo6JywGneVfceJfZu8o5wEMhlj9bpulJXSIFzh3rUsxABEWSj03yC9PORfUlzKJOvqrt04gOiwjVPS6Ay+h7iHYINcYaGp6clvjJ8/CoOr+Or3YbStfNS4jKGK0+zBfKBpAnZKXVZqbgriOKVfa7mRpJ30/Vi9k/0M7krE4V3tEpBUPvYO9mPtSbREOpxbguvpP6EL51/lam23h0OOey5BpFItFpblo/CXK/qnvLZXlmQZ5RPpeasWeiPdI7oIVG6Z/nWzBdY6B3dbnsSHgo168qWXeXHHXJXEcAWt2x0yBN6+WLU/2CcrFYIogDo3kcDkNQZSCPu9reLFGKI/YtSaEYn6X+Cu4r/qM/GQBRK6RrFlYoe147X41YJyml4HSRI6u0adOKbyBL/TLeyWW08DFVIFKT3dL7z+lgotQv+0q1j8Nes4tEIGOrPHMGkhqAwSt1t6leHrp/SbyNTb3G/o/NiQji9DuAlUgitcMT1UlxFywmLCYzTlpGviJq3aBoQbUHYUlJcWfEk4Q4E="
  revision_type: github
  application: ams-restore-6
  deployment_group: ams-restore-6-DG
  region: us-east-1
  on:
    branch: develop
    ruby: 2.5.3
env:
  matrix:
    secure: bhFHxEHJJKvXc1rXvhx6ip9anTD9vEZSUO+rkXDN3M2HOV3wco2Dt8HH+7gy1fS3A8l/5+VB1LQ0vwRzykQlGARuGIFFd9y9VaPsdAdjqJbTeD6Neb4SHFu7pOEbhfCfdkU/wOLTn1HQ46bl0u33E3fFeVLRyN1vyIuvYW3o9ZHpfhni8enGC9UbQt65DHUVSUCgynutKIWK/lIiiIzxrOhySjQN3u05/W38o1nwsQLi3pWjj20SLD7U42VPK72TzIqkfs4LPcOSb9we/EMdWhIcrfqRZrC/bbVXB/56Un4ZUF/83y0dQJoglcHB7S+rRCGSx48b2ZtojG6B2vdJ96fNuDePf1YhTkolt9VxDL70AZdIiszADSPYJY4OgI4bUInl2BQvxueXQqoZjLkXSxLdHTD5ImZwfYioV3qgmdWXKdmxc6+MRlOznKXE1oHJqCtnwFC47BN4gq7VZoQHiQdpx4BMOWF13b6qGtO8pJK59bGDQPSO+eskBpZfghad3aMJ9c8+FESkDN9la8HXxlwyZDVNpysVLFFZqFcQlWQ/NG3r/e/NhmAfs3uyqi+bC4dsgg4MInfNQnzErshpfbvTXFJ29cKYnWCY9cWD0zLau2VehXHUxdaBoPaBONM8K73i3aqv/2YMZwSYAy/1egDslliOdyDb9ACKkKt/g9w=
