---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.web.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: web
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
    component: web
