---
apiVersion: apps/v1 
kind: Ingress
metadata:
  name: {{ template "app.web.name" . }}-in
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  # tls:
  # - hosts:
  #   - {{ .Values.ingress.host }}
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - backend:
          serviceName: {{ template "app.web.name" . }}
          servicePort: 80
