{{- if and .Values.brandingVolume.enabled (not .Values.brandingVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "hyrax.fullname" . }}-branding
  labels:
    {{- include "hyrax.labels" . | nindent 4 }}
spec:
  {{ include "hyrax.sharedPvcAccessModes" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.brandingVolume.size }}
  storageClassName: {{ .Values.brandingVolume.storageClass }}
{{- end }}
