apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: ams-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: config.yml
      remoteRef:
        key: ams/ams2-app-credentials-demo
