apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aapb-ssh-key-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: aapb-ssh-key-{{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: aapb-ssh-key
      remoteRef:
        key: ams/aapb-ssh-key-{{ .Release.Name }}
