{{- if and .Values.uploadsVolume.enabled (not .Values.uploadsVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "hyrax.fullname" . }}-uploads
  labels:
    {{- include "hyrax.labels" . | nindent 4 }}
spec:
  {{ include "hyrax.sharedPvcAccessModes" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.uploadsVolume.size }}
  storageClassName: {{ .Values.uploadsVolume.storageClass }}
{{- end }}
