apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-to: "*"
type: Opaque
data:
  DB_PASSWORD: ${db_password}
  SOLR_ADMIN_PASSWORD: ${solr_admin_password}
  SMTP_PASSWORD: ${smtp_password}
  AWS_SECRET_KEY: ${aws_secret_key}
  CI_CLIENT_SECRET: ${ci_client_secret}
  CI_PASSWORD: ${ci_password}
