apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-to: "*"
type: Opaque
data:
  MYSQL_PASSWORD: ${mysql_password}
  SMTP_PASSWORD: ${smtp_password}
