apiVersion: v2
name: hyrax
description: An open-source, Samvera-powered digital repository system
type: application
version: 1.6.0
appVersion: 3.3.0
dependencies:
  - name: fcrepo
    version: 0.8.0
    repository: oci://ghcr.io/samvera
    condition: fcrepo.enabled
  - name: memcached
    version: 4.2.21
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: memcached.enabled
  - name: minio
    version: 6.7.2
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: minio.enabled
  - name: mariadb
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 9.5.1
    condition: mariadb.enabled
  - name: redis
    version: 10.7.16
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: redis.enabled
  - name: solr
    version: 1.0.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: solr.enabled
  - name: nginx
    version: 9.8.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: nginx.enabled
