apiVersion: v2
appVersion: 3.0.2
dependencies:
- condition: fcrepo.enabled
  name: fcrepo
  repository: oci://ghcr.io/samvera
  version: 0.8.0
- condition: memcached.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 4.2.21
- condition: minio.enabled
  name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 6.7.2
- name: mariadb
  version: 9.5.1
  repository: https://charts.bitnami.com/bitnami
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 10.7.16
- condition: solr.enabled
  name: solr
  repository: https://charts.bitnami.com/bitnami
  version: 1.0.1
description: An open-source, Samvera-powered digital repository system
name: hyrax
type: application
version: 0.22.0
