apiVersion: v2
name: hyrax
description: An open-source, Samvera-powered digital repository system
type: application
version: 1.6.0
appVersion: 3.7.1
dependencies:
  - name: memcached
    version: 0.1.24
    repository: https://kubelauncher.github.io/charts
    condition: memcached.enabled
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io
    condition: minio.enabled
  - name: redis
    version: 0.4.2
    repository: https://kubelauncher.github.io/charts
    condition: redis.enabled
  - name: nginx
    version: 25.0.11
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
