terms:
  - id: audio/mpeg
    term: audio/mpeg
  - id: audio/vnd.wave
    term: audio/vnd.wave
  - id: video/H264
    term: video/H264
  - id: video/mp4
    term: video/mp4
  - id: video/mpeg
    term: video/mpeg
  - id: video/quicktime
    term: video/quicktime