terms:
  - id: 1 inch audio tape
    term: 1 inch audio tape
  - id: 1 inch videotape
    term: 1 inch videotape
  - id: 1/2 inch digital audio tape
    term: 1/2 inch digital audio tape
  - id: 1/4 inch audio tape
    term: 1/4 inch audio tape
  - id: 1 inch videotape
    term: 1 inch videotape
  - id: 3/4 inch videotape
    term: 3/4 inch videotape
  - id: Audio cassette
    term: Audio cassette
  - id: Betacam
    term: Betacam
  - id: Betacam Digital (Digi-Beta)
    term: Betacam Digital (Digi Beta)
  - id: Betacam SP
    term: Betacam SP
  - id: Betacam SX
    term: Betacam SX
  - id: CD
    term: CD
  - id: D2
    term: D2
  - id: D3
    term: D3
  - id: D5
    term: D5
  - id: D9
    term: D9
  - id: DAT
    term: DAT
  - id: DVCAM
    term: DVCAM
  - id: DVCPRO
    term: DVCPRO
  - id: DVD
    term: DVD
  - id: "Film: 16mm"
    term: "Film: 16mm"
  - id: "Film: 35mm"
    term: "Film: 35mm"
  - id: HDCAM
    term: HDCAM
  - id: Hi8
    term: Hi8
  - id: MiniDV
    term: MiniDV
  - id: Minidisc
    term: Minidisc
  - id: S-VHS
    term: S-VHS
  - id: VHS
    term: VHS