terms:
  - id: Proxy
    term: Proxy
  - id: Mezzanine
    term: Mezzanine
  - id: Master
    term: Master
  - id: Preservation Master
    term: Preservation Master
  - id: Original footage
    term: Original footage
  - id: Clip reel
    term: Clip reel
  - id: Dub
    term: Dub
  - id: Rough cut
    term: Rough cut
  - id: Screening tape
    term: Screening tape
  - id: Stock footage
    term: Stock footage
  - id: Work print
    term: Work print
  - id: Work tape
    term: Work tape