terms:
  - id: Call-in
    term: Call-in
  - id: Children's
    term: Children's
  - id: Debate
    term: Debate
  - id: Documentary
    term: Documentary
  - id: Drama
    term: Drama
  - id: Educational
    term: Educational
  - id: Event Coverage
    term: Event Coverage
  - id: Fundraiser
    term: Fundraiser
  - id: Game Show
    term: Game Show
  - id: Instructional
    term: Instructional
  - id: Interview
    term: Interview
  - id: Magazine
    term: Magazine
  - id: Miniseries
    term: Miniseries
  - id: News Report
    term: News Report
  - id: Performance in a Studio
    term: Performance in a Studio
  - id: Performance for a Live Audience
    term: Performance for a Live Audience
  - id: Performance
    term: Performance
  - id: Promo
    term: Promo
  - id: Public Service Announcement
    term: Public Service Announcement
  - id: Radio Theater
    term: Radio Theater
  - id: Recorded Music
    term: Recorded Music
  - id: Special
    term: Special
  - id: Stand-up
    term: Stand-up
  - id: Radio Theater
    term: Radio Theater
  - id: Talk Show
    term: Talk Show
  - id: Town Hall Meeting
    term: Town Hall Meeting
  - id: Unedited
    term: Unedited