terms:
  - id: eng
    term: English
  - id: spa
    term: Spanish
  - id: fra
    term: French
  - id: ger
    term: German
  - id: ypk
    term: Yupik Languages
  - id: haw
    term: Hawaiian
  - id: heb
    term: Hebrew