terms:
  - id: abk
    term: abk
  - id: eng
    term: eng
  - id: fre
    term: fre
  - id: ger
    term: ger
  - id: hrv
    term: hrv
  - id: jpn
    term: jpn
  - id: khm
    term: khm
  - id: kor
    term: kor
  - id: lat
    term: lat
  - id: nav
    term: nav
  - id: pol
    term: pol
  - id: por
    term: por
  - id: rad
    term: rad
  - id: rus
    term: rus
  - id: spa
    term: spa
  - id: srp
    term: srp
  - id: tgl
    term: tgl
  - id: uzb
    term: uzb
  - id: vie
    term: vie
  - id: ypk
    term: ypk
  - id: zxx
    term: zxx
