terms:
  - id: English
    term: English
  - id: Spanish
    term: Spanish
  - id: French
    term: French
  - id: German
    term: German
  - id: Yupik Languages
    term: Yupik Languages
  - id: Hawaiian
    term: Hawaiian
  - id: Hebrew
    term: Hebrew