terms:
  - id: American Archive of Public Broadcasting
    term: American Archive of Public Broadcasting
  - id: Appalshop, Inc. (WMMT and Appalshop Films)
    term: Appalshop, Inc. (WMMT and Appalshop Films)
  - id: Arkansas Educational TV Network (AETN)
    term: Arkansas Educational TV Network (AETN)
  - id: BirdNote
    term: BirdNote
  - id: Bloomberg L.P.
    term: Bloomberg L.P.
  - id: Center for Asian American Media
    term: Center for Asian American Media
  - id: Chicago Public Radio (WBEZ-FM) and Vocalo.org
    term: Chicago Public Radio (WBEZ-FM) and Vocalo.org
  - id: Cincinnati Public Radio (WGUC-FM, WMUB-FM, WVXU-FM)
    term: Cincinnati Public Radio (WGUC-FM, WMUB-FM, WVXU-FM)
  - id: Colorado Public Television
    term: Colorado Public Television
  - id: Community Television Foundation of South Florida, Inc.
    term: Community Television Foundation of South Florida, Inc.
  - id: Connecticut Public Broadcasting
    term: Connecticut Public Broadcasting
  - id: CUNY TV
    term: CUNY TV
  - id: Detroit Public Television (aka DPTV and WTVS)
    term: Detroit Public Television (aka DPTV and WTVS)
  - id: Donald Voegeli
    term: Donald Voegeli
  - id: Film & Media Archive, Washington University in St. Louis
    term: Film & Media Archive, Washington University in St. Louis
  - id: Friends of WWOZ, Inc.
    term: Friends of WWOZ, Inc.
  - id: Georgia Public Broadcasting
    term: Georgia Public Broadcasting
  - id: Idaho Public Television
    term: Idaho Public Television
  - id: Illinois Public Media (WILL)
    term: Illinois Public Media (WILL)
  - id: Indiana University Libraries Moving Image Archive
    term: Indiana University Libraries Moving Image Archive
  - id : Internet Archive
    term: Internet Archive
  - id: Iowa Public Radio
    term: Iowa Public Radio
  - id: Iowa Public Television
    term: Iowa Public Television
  - id: James F. Voegeli
    term: James F. Voegeli
  - id: KAKM (Alaska Public Media)
    term: KAKM (Alaska Public Media)
  - id: KBOO Community Radio
    term: KBOO Community Radio
  - id: KCAW-FM (Raven Radio Foundation, Inc.)
    term: KCAW-FM (Raven Radio Foundation, Inc.)
  - id: KCPT (KCPT Public Television 19)
    term: KCPT (KCPT Public Television 19)
  - id: KCTS 9
    term: KCTS 9
  - id: KDLG-AM
    term: KDLG-AM
  - id: KDNA-FM
    term: KDNA-FM
  - id: KEET
    term: KEET
  - id: Ken Burns - Florentine Films
    term: Ken Burns - Florentine Films
  - id: KET - The Kentucky Network
    term: KET - The Kentucky Network
  - id: KEXP-FM
    term: KEXP-FM
  - id: KGLT-FM
    term: KGLT-FM
  - id: KGNU-FM
    term: KGNU-FM
  - id: KGTF (PBS Guam)
    term: KGTF (PBS Guam)
  - id: KMOS
    term: KMOS
  - id: KNBA-FM
    term: KNBA-FM
  - id: KNME
    term: KNME
  - id: KOCE/PBS SoCal
    term: KOCE/PBS SoCal
  - id: KOPN-FM - KOPN Community Radio
    term: KOPN-FM - KOPN Community Radio
  - id: KPCC
    term: KPCC
  - id: KQED
    term: KQED
  - id: KRCB
    term: KRCB
  - id: KSJN-FM (Minnesota Public Radio)
    term: KSJN-FM (Minnesota Public Radio)
  - id: KUCB (Unalaska Community Broadcasting/KIAL)
    term: KUCB (Unalaska Community Broadcasting/KIAL)
  - id: KUED
    term: KUED
  - id: KUHF-FM
    term: KUHF-FM
  - id: KUNM (aka KNME-FM)
    term: KUNM (aka KNME-FM)
  - id: KUOW Puget Sound Public Radio
    term: KUOW Puget Sound Public Radio
  - id: KUSC-FM
    term: KUSC-FM
  - id: KUSP-FM
    term: KUSP-FM
  - id: KUT Radio
    term: KUT Radio
  - id: KUVO-FM
    term: KUVO-FM
  - id: KVCR
    term: KVCR
  - id: KVIE
    term: KVIE
  - id: KWSO-FM (Warm Springs Community Radio)
    term: KWSO-FM (Warm Springs Community Radio)
  - id: KWSU/KTNW (Northwest Public Television)
    term: KWSU/KTNW (Northwest Public Television)
  - id: KXCI Community Radio
    term: KXCI Community Radio
  - id: KYUK
    term: KYUK
  - id: Library of Congress
    term: Library of Congress
  - id: Louisiana Public Broadcasting
    term: Louisiana Public Broadcasting
  - id: Maine Public Broadcasting
    term: Maine Public Broadcasting
  - id: Maryland Public Television
    term: Maryland Public Television
  - id: Media Burn
    term: Media Burn
  - id: Media for the Public Good, Inc. / Outcasting Media
  - id: Mississippi Public Broadcasting
    term: Mississippi Public Broadcasting
  - id: Mountain Lake PBS (WCFE)
    term: Mountain Lake PBS (WCFE)
  - id: Nashville Public Television
    term: Nashville Public Television
  - id: National Records and Archives Administration
    term: National Records and Archives Administration
  - id: New Hampshire Public Radio
    term: New Hampshire Public Radio
  - id: New Hampshire Public Television
    term: New Hampshire Public Television
  - id: New Jersey Network
    term: New Jersey Network
  - id: New York State Archives
    term: New York State Archives
  - id: NewsHour Productions
    term: NewsHour Productions
  - id: North Carolina Public Radio - WUNC
    term: North Carolina Public Radio - WUNC
  - id: OETA - Oklahoma Educational Television Authority
    term: OETA - Oklahoma Educational Television Authority
  - id: Oregon Public Broadcasting (OPB)
    term: Oregon Public Broadcasting (OPB)
  - id: Ozarks Public Broadcasting (KOZK/KOZJ)
    term: Ozarks Public Broadcasting (KOZK/KOZJ)
  - id: Pacifica Radio Archives
    term: Pacifica Radio Archives
  - id: PBS Hawaii (KHET)
    term: PBS Hawaii (KHET)
  - id: Pioneer Public Television
    term: Pioneer Public Television
  - id: Prairie Public Broadcasting
    term: Prairie Public Broadcasting
  - id: Public Broadcasting Atlanta
    term: Public Broadcasting Atlanta
  - id: Radio Bilingue
    term: Radio Bilingue
  - id: Rocky Mountain PBS (KRMA)
    term: Rocky Mountain PBS (KRMA)
  - id: Sesame Workshop
    term: Sesame Workshop
  - id: South Carolina Network (SCETV) (WRLK)
    term: South Carolina Network (SCETV) (WRLK)
  - id: Southern Oregon Public Television (KSYS/KFTS)
    term: Southern Oregon Public Television (KSYS/KFTS)
  - id: Stanford University
    term: Stanford University
  - id: The Nine Network of Public Media (formerly KETC)
    term: The Nine Network of Public Media (formerly KETC)
  - id: The Riverside Church
    term: The Riverside Church
  - id: The Walter J. Brown Media Archives & Peabody Awards Collection at the University of Georgia
    term: The Walter J. Brown Media Archives & Peabody Awards Collection at the University of Georgia
  - id: ThinkTV
    term: ThinkTV
  - id: Thirteen - New York Public Media (WNET)
    term: Thirteen - New York Public Media (WNET)
  - id: Twin Cities Public Television (KTCA-TV)
    term: Twin Cities Public Television (KTCA-TV)
  - id: UNC-TV
    term: UNC-TV
  - id: University of Alabama Center for Public Broadcasting
    term: University of Alabama Center for Public Broadcasting
  - id: University of Houston
    term: University of Houston
  - id: University of Maryland
    term: University of Maryland
  - id: Vegas PBS (KLVX)
    term: Vegas PBS (KLVX)
  - id: Vermont Public Radio - WVPR
    term: Vermont Public Radio - WVPR
  - id: Vermont Public Television
    term: Vermont Public Television
  - id: Vision Maker Media
    term: Vision Maker Media
  - id: WBLV-FM (Blue Lake Public Radio)
    term: WBLV-FM (Blue Lake Public Radio)
  - id: WBRA-TV
    term: WBRA-TV
  - id: WCNY
    term: WCNY
  - id: WCTE
    term: WCTE
  - id: WCVE
    term: WCVE
  - id: WDIY-FM
    term: WDIY-FM
  - id: WDVX-FM
    term: WDVX-FM
  - id: WEDU Florida Public Media
    term: WEDU Florida Public Media
  - id: WERU-FM (WERU Community Radio)
    term: WERU-FM (WERU Community Radio)
  - id: WFCR
    term: WFCR
  - id: WFIU-FM (Public Radio from Indiana University)
    term: WFIU-FM (Public Radio from Indiana University)
  - id: WFMU
    term: WFMU
  - id: WFYI-FM
    term: WFYI-FM
  - id: WGBH
    term: WGBH
  - id: WGBY
    term: WGBY
  - id: WGCU Public Media (WGCU-TV)
    term: WGCU Public Media (WGCU-TV)
  - id: WGVU Public TV & Radio
    term: WGVU Public TV & Radio
  - id: WHRO
    term: WHRO
  - id: WHUT-TV (Howard University Television)
    term: WHUT-TV (Howard University Television)
  - id: WHYY
    term: WHYY
  - id: WIAA-FM
    term: WIAA-FM
  - id: WIPR
    term: WIPR
  - id: Wisconsin Public Radio
    term: Wisconsin Public Radio
  - id: Wisconsin Public Television (WHA-TV)
    term: Wisconsin Public Television (WHA-TV)
  - id: WJCT-FM
    term: WJCT-FM
  - id: WKAR
    term: WKAR
  - id: WLVT (PBS39)
    term: WLVT (PBS39)
  - id: WMHT
    term: WMHT
  - id: WNED
    term: WNED
  - id: WNYC-FM
    term: WNYC-FM
  - id: WOJB-FM
    term: WOJB-FM
  - id: WOSU Public Media
    term: WOSU Public Media
  - id: WPBS
    term: WPBS
  - id: WQED-TV
    term: WQED-TV
  - id: WRFA-LP
    term: WRFA-LP
  - id: WRNI (Rhode Island Public Radio)
    term: WRNI (Rhode Island Public Radio)
  - id: WSIU Public Broadcasting
    term: WSIU Public Broadcasting
  - id: WSKG Public Broadcasting
    term: WSKG Public Broadcasting
  - id: WSRE
    term: WSRE
  - id: WTIP (North Shore Community Radio)
    term: WTIP (North Shore Community Radio)
  - id: WTIU (Public Television from Indiana University)
    term: WTIU (Public Television from Indiana University)
  - id: WUFT-TV
    term: WUFT-TV
  - id: WUMB-FM
    term: WUMB-FM
  - id: WUSF
    term: WUSF
  - id: WVIA
    term: WVIA
  - id: WVIZ/ideastream
    term: WVIZ/ideastream
  - id: WXPN-FM
    term: WXPN-FM
  - id: WXXI Public Broadcasting (WXXI-TV)
    term: WXXI Public Broadcasting (WXXI-TV)
  - id: WYCC-TV20 PBS Chicago
    term: WYCC-TV20 PBS Chicago
  - id: Wyoming PBS (KCWC)
    term: Wyoming PBS (KCWC)
  - id: WYSO-FM (WYSO Public Radio)
    term: WYSO-FM (WYSO Public Radio)
  - id: WYSU 88.5 FM
    term: WYSU 88.5 FM
