ingest_types:
  aapb_pbcore_zipped:
    label: "AAPB PBCore - Zipped"
    reader: "AAPB::BatchIngest::ZippedPBCoreReader"
    ingester: "AAPB::BatchIngest::PBCoreXMLItemIngester"
  aapb_csv_reader_1:
    label: "AAPB Spreadsheet Ingester"
    reader: "AAPB::BatchIngest::CSVReader"
    ingester: "AAPB::BatchIngest::CSVItemIngestor"
    reader_options:
      schema:
      - object_class: Asset
        ingest_type: new
        children:
        - object_class: Contribution
          ingest_type: new
        - object_class: PhysicalInstantiation
          ingest_type: new
  aapb_csv_reader_2:
    label: "AAPB Physical Instantiation Spreadsheet Ingester"
    reader: "AAPB::BatchIngest::CSVReader"
    ingester: "AAPB::BatchIngest::CSVItemIngestor"
    reader_options:
      schema:
      - object_class: Asset
        ingest_type: update
        attributes:
        - id
        children:
        - object_class: PhysicalInstantiation
          ingest_type: new
  aapb_csv_reader_3:
    label: "AAPB Asset Update Spreadsheet Ingester"
    reader: "AAPB::BatchIngest::CSVReader"
    ingester: "AAPB::BatchIngest::CSVItemIngestor"
    reader_options:
      schema:
      - object_class: Asset
        ingest_type: update
        attributes:
          - id
          - topics
  aapb_csv_reader_4:
    label: "AAPB Asset Multivalue Attribute Addition Spreadsheet Ingester"
    reader: "AAPB::BatchIngest::CSVReader"
    ingester: "AAPB::BatchIngest::CSVItemIngestor"
    reader_options:
      schema:
      - object_class: Asset
        ingest_type: add
        attributes:
          - id
          - topics
