test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: ams_development
  username: ams_development
  password: password
  host: localhost
  port: 3306
  # The time that MySQL2 lib will try to get a db connection.
  # Default is 5.
  # checkout_timeout: 10
  pool: 12

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PWD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306
  pool: 20
