# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] || 'ams' %>
  pool: 50
  timeout: 5000


development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['DB_TEST_NAME'] || 'ams_test' %>

staging:
  <<: *login


production:
  <<: *login
