# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: mysql2
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  pool: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', '25').to_i + 5 %>
  timeout: 5000


development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['TEST_DB'] %>

production:
  <<: *login
