development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
test:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
production:
  host: <%= ENV['REDIS_HOST'] || ENV['REDIS_SERVER'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  port: 6379
  network_timeout: 5
