# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  # Override to_partial_path to use generic catalog/document partial
  # instead of ActiveFedora-based partial that doesn't exist
  def to_partial_path
    'catalog/document'
  end
end
