# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  # Override to_partial_path to use generic catalog/document partial
  # instead of ActiveFedora-based partial that doesn't exist
  def to_partial_path
    'catalog/document'
  end
end
