replicaCount: 2

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: ams2.wgbh-mla.org
      paths:
        - path: /
  annotations:
    {
      kubernetes.io/ingress.class: "nginx",
      nginx.ingress.kubernetes.io/proxy-body-size: "0",
      cert-manager.io/cluster-issuer: letsencrypt-prod,
    }
  tls:
    - hosts:
        - ams2.wgbh-mla.org
      secretName: ams-prod-tls

extraEnvVars: &envVars
  - name: AAPB_HOST
    value: "americanarchive.org"
  - name: AAPB_SSH_KEY
    value: "/app/aapb/id_rsa"
  - name: AWS_ACCESS_KEY
    value: "AKIAIWFN3WW3WBIMKNCQ"
  - name: CI_CLIENT_ID
    value: "044dbd5644f640fb856a6131fd37e5cb"
  - name: CI_USERNAME
    value: "aapb_notifications@wgbh.org"
  - name: CI_WORKSPACE_ID
    value: "051303c1c1d24da7988128e6d2f56aa9"
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/config"
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: "10.0.4.93"
  - name: DB_NAME
    value: hyrax
  - name: DB_PORT
    value: "5432"
  - name: DB_USERNAME
    value: ams_user
  - name: FCREPO_BASE_PATH
    value: /prod
  - name: FCREPO_HOST
    value: 10.0.4.93:8080
  - name: FCREPO_PATH
    value: /fcrepo-webapp-4.7.5/rest
  - name: FCREPO_URL
    value: http://10.0.4.93:8080/fcrepo-webapp-4.7.5/rest
  - name: HYRAX_VALKYRIE
    value: "true"
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: MAIL_DELIVERY_METHOD
    value: "smtp"
  - name: NODE_OPTIONS
    value: "--openssl-legacy-provider"
  - name: PRODUCTION_HOST
    value: "ams2.wgbh-mla.org"
  - name: RAILS_CACHE_STORE_URL
    value: redis://:prod@ams-prod-redis-master:6379/ams-prod
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: ams-prod-redis-master
  - name: REDIS_PASSWORD
    value: prod
  - name: REDIS_PREFIX
    value: ams-prod
  - name: REDIS_SERVER
    value: redis://:prod@ams-prod-redis-master:6379
  - name: S3_EXPORT_BUCKET
    value: "ams-edge.wgbh-mla.org"
  - name: S3_EXPORT_DIR
    value: "ip-10-10-1-77"
  - name: SENTRY_DSN
    value: https://6f6e6b5f54234b5bb2218786c3493a37@o1008683.ingest.sentry.io/6745030
  - name: SENTRY_ENVIRONMENT
    value: "production"
  - name: SENTRY_TRACES_SAMPLE_RATE
    value: "0.1"
  - name: SETTINGS__BULKRAX__ENABLED
    value: "false"
  - name: SIDEKIQ_CONCURRENCY
    value: "1"
  - name: SIDEKIQ_REDIS_URL
    value: "redis://:prod@ams-prod-redis-master:6379/0"
  - name: SMTP_ADDRESS
    value: "email-smtp.us-east-1.amazonaws.com"
  - name: SMTP_AUTHENTICATION
    value: "login"
  - name: SMTP_ENABLE_STARTTLS
    value: "true"
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_USERNAME
    value: "AKIAINCFFPY4ILW2LNJQ"
  - name: SOLR_HOST
    value: 10.0.4.93
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://10.0.4.93:8983/solr/ams
  - name: VALKYRIE_ID_TYPE
    value: string

worker:
  replicaCount: 1
  importReplicaCount: 1
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars

importWorker:
  extraEnvVars:
    - name: SIDEKIQ_CONCURRENCY
      value: "10"

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false

mariadb:
  enabled: false

externalMariadb:
  db:
    host: ams-prod-rails-db.cmrjt7rckp5r.us-east-1.rds.amazonaws.com
  auth:
    username: hyrax
    database: hyrax

redis:
  cluster:
    enabled: false
  password: prod

solr:
  enabled: false

externalFcrepoHost: 10.0.4.93

externalSolrHost: 10.0.4.93
externalSolrUser: admin
externalSolrCollection: "ams"
externalSolrPassword: "-"
loadSolrConfigSet: false
extraSecret: true
