name: "Deploy"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        required: true
        default: 'demo'
        type: choice
        options:
          - staging
          - demo
          - prod
          - alpha
          - bravo
          - charlie
          - delta
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  REGISTRY: ghcr.io

jobs:
  deployment:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.9.4
    environment: ${{ inputs.environment }}
    env:
      HELM_EXPERIMENTAL_OCI: 1
      HELM_RELEASE_NAME: ${{ github.event.repository.name }}-${{ inputs.environment }}
      KUBE_NAMESPACE: ${{ github.event.repository.name }}-${{ inputs.environment }}
      HELM_EXTRA_ARGS: >
        --values ops/${{ inputs.environment }}-deploy.yaml
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      ENCODED_ENV_FILE: ${{ secrets.ENCODED_ENV_FILE }}
      KUBECONFIG: ./kubeconfig.yml
    steps:
      - name: Set env
        run: >-
          echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
          echo ${HEAD_TAG::8}
        env:
          HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
        shell: bash
      - name: Downcase repo
        env:
          REPO: "${{ inputs.image_name || github.repository }}"
        run: |
          echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ inputs.token }}
          clean: false
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Do deploy
        run: |
          echo $KUBECONFIG_FILE | base64 -d > $KUBECONFIG;
          DOLLAR=$ envsubst < ops/${{ inputs.environment }}-deploy.tmpl.yaml > ops/${{ inputs.environment }}-deploy.yaml;
          export DEPLOY_TAG=${TAG};
          export DEPLOY_IMAGE=ghcr.io/${REPO_LOWER};
          export WORKER_IMAGE=ghcr.io/${REPO_LOWER}/worker;
          ./bin/helm_deploy ${{ inputs.k8s-release-name || format('{0}-{1}', github.event.repository.name, inputs.environment) }} ${{ inputs.k8s-namespace || format('{0}-{1}', github.event.repository.name, inputs.environment) }}
