name: "Deploy Staging"
on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    container: dtzar/helm-kubectl:3.9.4
    env:
      DEPLOY_IMAGE: ghcr.io/${{ secrets.GITHUB_REPOSITORY }}
      WORKER_IMAGE: ghcr.io/${{ secrets.GITHUB_REPOSITORY }}/worker
      HELM_EXPERIMENTAL_OCI: 1
      HELM_RELEASE_NAME: gbh-staging
      KUBE_NAMESPACE: gbh-staging
      HELM_EXTRA_ARGS: >
        --values ops/staging-deploy.yaml
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE_STAGING }}
      KUBECONFIG: ./kubeconfig.yml
    steps:
      - name: Set env
        run: >-
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV;
          echo "DEPLOY_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV;
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Do deploy
        run: >-
          echo $KUBECONFIG_FILE | base64 --decode > $KUBECONFIG
          DOLLAR=$ envsubst < ops/staging-deploy.tmpl.yaml > ops/staging-deploy.yaml;
          ./bin/helm_deploy gbh-staging gbh-staging
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
