name: "Retag on merge"
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Downcase repo
        run: |
          echo "REPO_LOWER=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'
      - name: Retag web to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ${{ env.REGISTRY }}
          name: ${{ env.REPO_LOWER }}
          old_tag: ${{ env.TAG }}
          new_tag: latest
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retag worker to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ${{ env.REGISTRY }}
          name: ${{ env.REPO_LOWER }}/worker
          old_tag: ${{ env.TAG }}
          new_tag: latest
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
